# netlify.toml

[build]
  # Comando para instalar dependencias y construir el proyecto
  command = "npm install && ionic build"
  # Directorio REAL donde están los archivos compilados
  publish = "www/browser" # <--- Corregido aquí

# Regla de redirección (sigue igual y es necesaria)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200