# netlify.toml (Prueba con ng build)

[build]
  # Usamos ng build en lugar de ionic build
  command = "npm install && ng build --configuration production"
  # Y ajustamos el directorio de publicación a 'www'
  publish = "www" # <--- ¡Asegúrate de cambiar esto!

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200